require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'
use_frameworks!

target 'ReactNative63UseFrameworks' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'ReactNative63UseFrameworksTests' do
    inherit! :complete
    # Pods for testing
  end
end

target 'ReactNative63UseFrameworks-tvOS' do
  # Pods for ReactNative63UseFrameworks-tvOS

  target 'ReactNative63UseFrameworks-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
